FROM python:3.11-slim

WORKDIR /app

COPY requirements.train.txt .
RUN pip install --no-cache-dir -r requirements.train.txt

COPY src/ ./src/
COPY data/ ./data/

CMD ["python", "src/training/train.py"]

ENV GIT_PYTHON_REFRESH=quiet